## 数据库连接池配置
spring:
  datasource:
    platform: mysql                        # 指定数据源类型
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=GMT%2B8
    username: root
    password: 123
  jmx:
    default-domain: mybatis
mybatis:
  # 指定实体类包路径
  typeAliasesPackage: com.example.spring.bean
  # 指定xml文件扫描路径
  mapper-locations: classpath*:mapper/*.xml
#  页面
  thymeleaf:
    cache: false
#  mail:
#    host: smtp.163.com
#    username: 你的账号
#    password: 你的密码
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
logging:
  level:
    com:
      springboot:
        mapper: debug
# 缓存
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
  cache:
    ehcache:
      config: 'classpath:ehcache.xml'

management:
  security:
    enabled: false #关掉安全认证
#  port: 80
#  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true

